# Generated by Django 4.2.7 on 2023-12-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("species_app_vm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="speciescentraldatabank",
            name="taxon_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Taxon ID:"),
        ),
        migrations.AddField(
            model_name="speciesuserdatabank",
            name="taxon_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Taxon ID:"),
        ),
        migrations.AlterField(
            model_name="speciescentraldatabank",
            name="latin_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Vetenskapligt namn:",
            ),
        ),
        migrations.AlterField(
            model_name="speciescentraldatabank",
            name="source",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Källa:"
            ),
        ),
        migrations.AlterField(
            model_name="speciescentraldatabank",
            name="species_name_common",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Svenskt namn:"
            ),
        ),
        migrations.AlterField(
            model_name="speciesuserdatabank",
            name="last_update_date",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Senast uppdaterad:"
            ),
        ),
        migrations.AlterField(
            model_name="speciesuserdatabank",
            name="latin_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Vetenskapligt namn:",
            ),
        ),
        migrations.AlterField(
            model_name="speciesuserdatabank",
            name="source",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Källa:"
            ),
        ),
        migrations.AlterField(
            model_name="speciesuserdatabank",
            name="species_data",
            field=models.TextField(blank=True, null=True, verbose_name="Information:"),
        ),
        migrations.AlterField(
            model_name="speciesuserdatabank",
            name="species_name_common",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Svenskt namn:"
            ),
        ),
    ]
