# Generated by Django 4.2.7 on 2023-11-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app_vm", "0002_audit_log"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audit_log",
            options={
                "verbose_name": "Revisionslogg",
                "verbose_name_plural": "Revisionslogg",
            },
        ),
        migrations.AlterModelOptions(
            name="user_additional",
            options={
                "verbose_name": "Ytterligare användarinformation",
                "verbose_name_plural": "Ytterligare användarinformation",
            },
        ),
        migrations.AlterField(
            model_name="audit_log",
            name="action",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Aktion:"
            ),
        ),
        migrations.AlterField(
            model_name="audit_log",
            name="details",
            field=models.TextField(blank=True, null=True, verbose_name="Information:"),
        ),
        migrations.AlterField(
            model_name="audit_log",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Tidslag:"
            ),
        ),
        migrations.AlterField(
            model_name="user_additional",
            name="department",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Avdelning:"
            ),
        ),
        migrations.AlterField(
            model_name="user_additional",
            name="job_title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Jobbtitel:"
            ),
        ),
        migrations.AlterField(
            model_name="user_additional",
            name="organization_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Organisation:"
            ),
        ),
        migrations.AlterField(
            model_name="user_additional",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Telefonnummer:"
            ),
        ),
        migrations.AlterField(
            model_name="user_additional",
            name="role",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Roll:"
            ),
        ),
    ]
