# Generated by Django 4.2.7 on 2023-12-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app_vm", "0003_alter_audit_log_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_additional",
            name="Payment_latest_invoice",
            field=models.BooleanField(
                default=False, verbose_name="Betalat senaste faktura:"
            ),
        ),
        migrations.AddField(
            model_name="user_additional",
            name="active_account",
            field=models.BooleanField(default=True, verbose_name="Aktivt konto:"),
        ),
        migrations.AddField(
            model_name="user_additional",
            name="payment_adress",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Faktura adress:"
            ),
        ),
        migrations.AddField(
            model_name="user_additional",
            name="payment_comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Kommentar om kund:"
            ),
        ),
        migrations.AddField(
            model_name="user_additional",
            name="payment_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Senaste betalningsdatum:"
            ),
        ),
        migrations.AddField(
            model_name="user_additional",
            name="payment_email",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Faktura e-postadress:",
            ),
        ),
        migrations.AddField(
            model_name="user_additional",
            name="payment_invoice_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Nuvarande fakturadatum:"
            ),
        ),
        migrations.AddField(
            model_name="user_additional",
            name="payment_invoice_due_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Nuvarande förfallodatum:"
            ),
        ),
        migrations.AddField(
            model_name="user_additional",
            name="payment_invoice_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nuvarande fakturanummer:",
            ),
        ),
        migrations.AddField(
            model_name="user_additional",
            name="payment_price",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Pris per månad:"
            ),
        ),
        migrations.AddField(
            model_name="user_additional",
            name="payment_reference",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Deras referens:"
            ),
        ),
        migrations.AddField(
            model_name="user_additional",
            name="payment_telephone",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Faktura telefonnummer:",
            ),
        ),
    ]
