# Generated by Django 4.2.7 on 2023-12-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app_vm", "0004_user_additional_payment_latest_invoice_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_additional",
            name="payment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Senaste betalningsdatum:"
            ),
        ),
        migrations.AlterField(
            model_name="user_additional",
            name="payment_invoice_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Nuvarande fakturadatum:"
            ),
        ),
        migrations.AlterField(
            model_name="user_additional",
            name="payment_invoice_due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Nuvarande förfallodatum:"
            ),
        ),
    ]
