# Generated by Django 4.2.7 on 2023-12-01 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth_app_vm", "0005_alter_user_additional_payment_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_additional",
            name="Payment_latest_invoice",
        ),
        migrations.RemoveField(
            model_name="user_additional",
            name="active_account",
        ),
        migrations.RemoveField(
            model_name="user_additional",
            name="payment_adress",
        ),
        migrations.RemoveField(
            model_name="user_additional",
            name="payment_comment",
        ),
        migrations.RemoveField(
            model_name="user_additional",
            name="payment_date",
        ),
        migrations.RemoveField(
            model_name="user_additional",
            name="payment_email",
        ),
        migrations.RemoveField(
            model_name="user_additional",
            name="payment_invoice_date",
        ),
        migrations.RemoveField(
            model_name="user_additional",
            name="payment_invoice_due_date",
        ),
        migrations.RemoveField(
            model_name="user_additional",
            name="payment_invoice_number",
        ),
        migrations.RemoveField(
            model_name="user_additional",
            name="payment_price",
        ),
        migrations.RemoveField(
            model_name="user_additional",
            name="payment_reference",
        ),
        migrations.RemoveField(
            model_name="user_additional",
            name="payment_telephone",
        ),
        migrations.CreateModel(
            name="User_payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active_account",
                    models.BooleanField(default=True, verbose_name="Aktiverat konto:"),
                ),
                (
                    "Payment_latest_invoice",
                    models.BooleanField(
                        default=False, verbose_name="Betalat senaste faktura:"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Senaste betalningsdatum:"
                    ),
                ),
                (
                    "payment_price",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Pris per månad:"
                    ),
                ),
                (
                    "payment_invoice_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nuvarande fakturanummer:",
                    ),
                ),
                (
                    "payment_invoice_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Nuvarande fakturadatum:"
                    ),
                ),
                (
                    "payment_invoice_due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Nuvarande förfallodatum:"
                    ),
                ),
                (
                    "payment_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Fakturerings e-postadress:",
                    ),
                ),
                (
                    "payment_adress",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Faktureringsadress:",
                    ),
                ),
                (
                    "payment_telephone",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Kontakttelefonnummer:",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Deras referens:",
                    ),
                ),
                (
                    "payment_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Kommentar om kund:"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Betalningsinformation",
                "verbose_name_plural": "Betalningsinformation",
            },
        ),
    ]
