# Generated by Django 4.2.7 on 2023-12-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app_vm", "0006_remove_user_additional_payment_latest_invoice_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user_payment",
            options={
                "verbose_name": "Betalnings- och kontoinformation",
                "verbose_name_plural": "Betalnings- och kontoinformation",
            },
        ),
        migrations.AlterField(
            model_name="user_payment",
            name="payment_adress",
            field=models.TextField(
                blank=True, null=True, verbose_name="Faktureringsadress:"
            ),
        ),
        migrations.AlterField(
            model_name="user_payment",
            name="payment_telephone",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Kontaktelefonnummer:",
            ),
        ),
    ]
