# Generated by Django 5.0 on 2023-12-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app_vm", "0008_alter_user_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_additional",
            name="account_type",
            field=models.BooleanField(default=False, verbose_name="Kontotyp:"),
        ),
        migrations.AddField(
            model_name="user_additional",
            name="organization_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Organisationsnummer:",
            ),
        ),
        migrations.AlterField(
            model_name="user_additional",
            name="organization_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Organisationsnamn:"
            ),
        ),
    ]
