# Generated by Django 5.0 on 2023-12-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app_vm", "0009_user_additional_account_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_additional",
            name="account_type",
            field=models.BooleanField(default=False, verbose_name="Företagskonto:"),
        ),
    ]
