# Generated by Django 4.2.8 on 2023-12-05 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "survey_app_vm",
            "0002_group_hydromorfologisk_group_kartlaggningstyp_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Biotop_other",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_code", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=255)),
                ("specific_code", models.CharField(max_length=100, unique=True)),
                ("biotopemark", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Ecosystem_category_hav_ant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_code", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Ecosystem_category_hav_nat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_code", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Ecosystem_category_mark_ant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_code", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Ecosystem_category_mark_nat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_code", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Ecosystem_category_sotv_ant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_code", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Ecosystem_category_sotv_nat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_code", models.CharField(max_length=100, unique=True)),
                ("category", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Vattendrag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_code", models.CharField(max_length=100, unique=True)),
                ("biotopemark", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app_vm.ecosystem_category_sotv_nat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Values_sotv_ant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_code", models.CharField(max_length=100, unique=True)),
                ("biotopemark", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app_vm.ecosystem_category_sotv_ant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Values_mark_ant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_code", models.CharField(max_length=100, unique=True)),
                ("biotopemark", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app_vm.ecosystem_category_mark_ant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Values_hav_ant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_code", models.CharField(max_length=100, unique=True)),
                ("biotopemark", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app_vm.ecosystem_category_hav_ant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skog_buskmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_code", models.CharField(max_length=100, unique=True)),
                ("biotopemark", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app_vm.ecosystem_category_mark_nat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sjo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_code", models.CharField(max_length=100, unique=True)),
                ("biotopemark", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app_vm.ecosystem_category_sotv_nat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Naturligt_bar_jord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_code", models.CharField(max_length=100, unique=True)),
                ("biotopemark", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app_vm.ecosystem_category_mark_nat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Naturliga_smavatten",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_code", models.CharField(max_length=100, unique=True)),
                ("biotopemark", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app_vm.ecosystem_category_sotv_nat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Naturlig_grasmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_code", models.CharField(max_length=100, unique=True)),
                ("biotopemark", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app_vm.ecosystem_category_mark_nat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Myr_mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_code", models.CharField(max_length=100, unique=True)),
                ("biotopemark", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app_vm.ecosystem_category_mark_nat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marint_ostersjon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_code", models.CharField(max_length=100, unique=True)),
                ("biotopemark", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app_vm.ecosystem_category_hav_nat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Marint_atlantiskt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_code", models.CharField(max_length=100, unique=True)),
                ("biotopemark", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app_vm.ecosystem_category_hav_nat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kalfjall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_code", models.CharField(max_length=100, unique=True)),
                ("biotopemark", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app_vm.ecosystem_category_mark_nat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Berg_och_sten",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_code", models.CharField(max_length=100, unique=True)),
                ("biotopemark", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app_vm.ecosystem_category_mark_nat",
                    ),
                ),
            ],
        ),
    ]
