# Generated by Django 5.0 on 2023-12-14 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey_app_vm", "0003_biotop_other_ecosystem_category_hav_ant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Strand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attributes", models.CharField(max_length=255)),
                (
                    "group_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey_app_vm.group_vardeelement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
