# Generated by Django 4.2.8 on 2023-12-04 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project_app_vm", "0002_polygondata_pointdata_linedata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linedata",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_data",
                to="project_app_vm.project",
            ),
        ),
        migrations.AlterField(
            model_name="pointdata",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="point_data",
                to="project_app_vm.project",
            ),
        ),
        migrations.AlterField(
            model_name="polygondata",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polygon_data",
                to="project_app_vm.project",
            ),
        ),
    ]
