# Generated by Django 5.0 on 2024-01-17 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_app_vm",
            "0003_alter_linedata_project_alter_pointdata_project_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoJSONFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                ("geojson_data", models.JSONField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_app_vm.project",
                    ),
                ),
            ],
        ),
    ]
