# Generated by Django 5.0 on 2024-01-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_app_vm",
            "0006_rename_executing_organization_project_executing_organization_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="object_version",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
