# Generated by Django 5.0 on 2024-01-29 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_app_vm", "0007_alter_project_object_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="MappingInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "limitations_uncertainties",
                    models.TextField(
                        blank=True, verbose_name="Begränsningar och osäkerheter"
                    ),
                ),
                (
                    "methods_scope",
                    models.TextField(blank=True, verbose_name="Metoder och omfattning"),
                ),
                (
                    "minimum_mapping_unit",
                    models.TextField(verbose_name="Minsta karteringsenhet"),
                ),
                (
                    "mapping_type",
                    models.CharField(
                        max_length=255, verbose_name="Typ av kartläggning"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferenceMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Datum")),
                ("source", models.CharField(max_length=255, verbose_name="Källa")),
                (
                    "object_identity",
                    models.CharField(max_length=255, verbose_name="Objektidentitet"),
                ),
                ("object_version", models.IntegerField(verbose_name="Objektversion")),
                (
                    "reference_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Datum"),
                ),
                (
                    "event_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Händelse"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Kortnamn"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="Namn"),
                ),
                (
                    "reference_identity",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="Identitet",
                    ),
                ),
                ("link", models.URLField(blank=True, verbose_name="Länk")),
                (
                    "namespace",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Namnrymd"
                    ),
                ),
                (
                    "specific_reference",
                    models.TextField(blank=True, verbose_name="Specifik referens"),
                ),
                (
                    "valid_from",
                    models.DateTimeField(verbose_name="Version giltig från"),
                ),
                ("valid_to", models.DateTimeField(verbose_name="Version giltig till")),
            ],
        ),
    ]
