# Generated by Django 5.0 on 2024-01-29 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_app_vm", "0008_mappinginformation_referencematerial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MappingInformation",
        ),
        migrations.DeleteModel(
            name="ReferenceMaterial",
        ),
    ]
