# Generated by Django 5.0 on 2024-02-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_app_vm", "0011_projectimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimage",
            name="map_object_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Map Object ID"
            ),
        ),
    ]
