# Generated by Django 5.0 on 2024-02-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_app_vm", "0012_projectimage_map_object_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="saved_object_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
