# Generated by Django 4.2.8 on 2023-12-04 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "project_app_vm",
            "0003_alter_linedata_project_alter_pointdata_project_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_data", models.FileField(upload_to="reports/")),
                ("generated_date", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_app_vm.project",
                    ),
                ),
            ],
        ),
    ]
