# Generated by Django 5.0 on 2023-12-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report_app_vm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="report_data",
            field=models.FileField(upload_to="project_reports/"),
        ),
    ]
